package com.zorm.jdbc;

import java.sql.PreparedStatement;

public interface StatementPreparer {
	public PreparedStatement prepareStatement(String sql);
	public PreparedStatement prepareStatement(String sql, boolean isCallable);
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys);
	public PreparedStatement prepareStatement(String sql, String[] columnNames);
	public PreparedStatement prepareQueryStatement(String sql, boolean isCallable, ScrollMode scrollMode);
}
